name: aws-codecommit-sync
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          aws-region: ap-south-1

      - name: Sync GitHub Repository to AWS CodeCommit
        uses: inception-health/sync-up-to-codecommit-action@main
        with:
          codecommit_url: https://git-codecommit.ap-south-1.amazonaws.com/v1/repos/TEST_DEV
